package telegram.epsilon_robot.telegramBot.botStates;

public enum State {
    COIN_FOUND_SUCCESSFULLY,
    COIN_RESEARCH,
    NEW_USER,
    ERROR,
    BACK,
    MAIN_MENU,
    GET_SELECTED_COIN_COST,
    MY_ACCOUNT,
    ACCOUNT_CREATED_RECENTLY,
    USER_MANUAL,
    COIN_SEARCH,
    TOP_30,
    TOP_10_ROSE_IN_PRICE_IN_24H,
    TOP_10_FELL_IN_PRICE_IN_24H,
    ADD_TO_LIST,
    DELETE_FROM_LIST,
    ANABLE_ALERTS,
    COIN_STATISTICS,
    DELETE_ACCOUNT,
    ACCOUNT_DELETED,
    HOW_TO_FIND_OUT_THE_VALUE_OF_A_COIN,
    WHY_DO_I_NEED_THE_ACCOUNT,
    ALERT_OF_COIN_RISING_AND_FALLING,
    HOW_MUCH_DOES_IT_COST,
    NEWS_AND_RECOMMENDATIONS
}
